Fix for hl2b times
LINK1733/backlog-ninja pull request #17
Opened 2022-03-03 23:20 UTC by LINK1733

Fixed issue where the page would crash if there were less than 3 times for a game. 

Changed the style on the carousel arrows to not display the buttons for the carousel if there's only one game.

2022-03-04 02:57 UTC, sheodox requested changes

2022-03-04 02:57 UTC, sheodox commented on src/static/components/gameTime.js
> +
This is really weird to have inside the `gameTimes.map` loop!

Looks like you could disable this by setting `controls={false}` on the `<Carousel>` https://react-bootstrap.github.io/components/carousel/#api

2022-03-08 22:58 UTC, LINK1733 commented on src/static/components/gameTime.js
> +
Ok i've switched how this is done now to using the controls prop.

2022-03-09 04:18 UTC, LINK1733 commented
You right, you right. I misread the docs and just saw prettier ignore and did that lol.

2022-03-09 15:34 UTC, merged